version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "3000:3000"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    platform: linux/amd64
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
