apiVersion: v1
kind: Service
metadata:
  name: mikroserwis-a-service
  labels:
    app: mikroserwis-a
spec:
  type: LoadBalancer
  selector:
    app: mikroserwis-a
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000