apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-lab9
  template:
    metadata:
      labels:
        app: nginx-lab9
    spec:
      containers:
      - name: nginx
        image: gollet/nginx-lab9-zad2:latest
        ports:
        - containerPort: 80