apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-b-deployment
  labels:
    app: mikroserwis-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikroserwis-b
  template:
    metadata:
      labels:
        app: mikroserwis-b
    spec:
      containers:
        - name: mikroserwis-b
          image: mikroserwis-b:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_HOST
            - name: MONGO_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_PORT
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "0.5"
