apiVersion: v1
kind: Service
metadata:
  name: mikroserwis-b-service
  labels:
    app: mikroserwis-b
spec:
  type: ClusterIP
  selector:
    app: mikroserwis-b
  ports:
  - port: 3001
    targetPort: 3001