apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bXl1c2Vy
  MONGO_INITDB_ROOT_PASSWORD: bXlwYXNzd29yZA==

  # echo -n 'myuser' | base64
  # echo -n 'mypassword' | base64