apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-b-deployment
  labels:
    app: mikroserwis-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikroserwis-b
  template:
    metadata:
      labels:
        app: mikroserwis-b
    spec:
      containers:
      - name: mikroserwis-b
        image: mikroserwis-b:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URL
          value: mongodb://mongo-service:27017/mydb
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "0.5"