version: '3.8'

services:
  db:
    image: mongo:${MONGO_VERSION}
    container_name: db
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - net_A

  server:
    build: ./server
    container_name: server
    depends_on:
      - db
    ports:
      - "3003:3000"
    environment:
      - MONGO_URL=mongodb://db:27017
    networks:
      - net_A

volumes:
  mongo-data:

networks:
  net_A:
    driver: bridge